/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ourgrid_epanetgrid_ToolkitAdapter */

#ifndef _Included_org_ourgrid_epanetgrid_ToolkitAdapter
#define _Included_org_ourgrid_epanetgrid_ToolkitAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enEpanet
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enEpanet
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enOpen
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enOpen
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enClose
  (JNIEnv *, jobject);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetNodeIndex
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetNodeIndex
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetNodeId
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetNodeId
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetNodeType
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetNodeType
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetNodeValue
 * Signature: (IIF)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetNodeValue
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetLinkIndex
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetLinkIndex
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetLinkID
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetLinkID
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetLinkType
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetLinkType
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetLinkNodes
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetLinkNodes
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetLinkValue
 * Signature: (IIF)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetLinkValue
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetPatternID
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetPatternID
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetPatternIndex
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetPatternIndex
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetPatternLen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetPatternLen
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetPatternValue
 * Signature: (IIF)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetPatternValue
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetControl
 * Signature: (IIIFIF)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetControl
  (JNIEnv *, jobject, jint, jint, jint, jfloat, jint, jfloat);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetFlowUnits
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetFlowUnits
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetTimeParam
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetTimeParam
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetQualType
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetQualType
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetOption
 * Signature: (IF)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetOption
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetVersion
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSetControl
 * Signature: (IIIFIF)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSetControl
  (JNIEnv *, jobject, jint, jint, jint, jfloat, jint, jfloat);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSetNodeValue
 * Signature: (IIF)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSetNodeValue
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSetLinkValue
 * Signature: (IIF)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSetLinkValue
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSetPattern
 * Signature: (IFI)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSetPattern
  (JNIEnv *, jobject, jint, jfloat, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSetPatternValue
 * Signature: (IIF)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSetPatternValue
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSetQualType
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSetQualType
  (JNIEnv *, jobject, jint, jstring, jstring, jstring);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSetTimeParam
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSetTimeParam
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSetOption
 * Signature: (IF)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSetOption
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSaveHydFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSaveHydFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enUseHydFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enUseHydFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSolveH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSolveH
  (JNIEnv *, jobject);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enOpenH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enOpenH
  (JNIEnv *, jobject);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enInitH
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enInitH
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enRunH
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enRunH
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enNextH
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enNextH
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enCloseH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enCloseH
  (JNIEnv *, jobject);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSolveQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSolveQ
  (JNIEnv *, jobject);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enOpenQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enOpenQ
  (JNIEnv *, jobject);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enInitQ
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enInitQ
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enRunQ
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enRunQ
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enNextQ
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enNextQ
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enStepQ
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enStepQ
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enCloseQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enCloseQ
  (JNIEnv *, jobject);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSaveH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSaveH
  (JNIEnv *, jobject);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSaveInpFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSaveInpFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enReport
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enReport
  (JNIEnv *, jobject);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enResetReport
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enResetReport
  (JNIEnv *, jobject);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSetReport
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSetReport
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enSetStatusReport
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enSetStatusReport
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ourgrid_epanetgrid_ToolkitAdapter
 * Method:    enGetError
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_ourgrid_epanetgrid_ToolkitAdapter_enGetError
  (JNIEnv *, jobject, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
